# This workflow executes the various RepoSense tests

name: JDK 8 CI

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  ubuntu-1604:
    name: Ubuntu 16.04 JDK 8
    runs-on: ubuntu-16.04
    env:
      NODE_VERSION="lts/*"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Verify Java version
      run: echo -e "Actual JDK in use -- "; java -version

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Set up Gradle caching
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up Node caching
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run environmental checks
      run: ./config/travis/run-checks.sh

    - name: Run linter
      run: |
        npm install
        npm run lint

    - name: Build with Gradle
      run: time ./gradlew clean checkstyleMain checkstyleTest test systemTest coverage

    - name: Run code coverage
      if: ${{ success() }}
      run: bash <(curl -s https://codecov.io/bash)

    - name: Deploy to surge.sh
      if: ${{ success() }}
      run: |
        git fetch --all && git config --global user.email "-" && git config --global user.name "-" && ./gradlew run -Dargs="--since d1"
        npm install -g surge
        npm install -g markbind-cli
        (cd docs && markbind build)
        ./config/travis/deploy-surge.sh

  macos-1015:
    name: macOS 10.15 JDK 8
    runs-on: macos-10.15
    env:
      HOMEBREW_NO_AUTO_UPDATE=1 # Prevent time-consuming brew update

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Verify Java version
      run: echo -e "Actual JDK in use -- "; java -version

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Set up Gradle caching
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up Node caching
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run environmental checks
      run: ./config/travis/run-checks.sh

    - name: Run linter
      run: |
        npm install
        npm run lint

    - name: Build with Gradle
      run: time ./gradlew clean checkstyleMain checkstyleTest test systemTest coverage
