# This workflow deploys a RepoSense report and the MarkBind documentation
# website to surge.sh in a secure manner for pull requests

name: Surge.sh pending build

on:
  pull_request_target:
    branches-ignore:
      - gh-pages

jobs:
  deploy:
    name: Surge.sh pending build
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "lts/*"
      ACTIONS_PULL_REQUEST_HEAD: ${{ github.event.pull_request.head.sha }}
      ACTIONS_PULL_REQUEST_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update PR checklist for surge.sh as queued
      run: |
        mkdir -p ./pr
        ./config/gh-actions/deploy-surge.sh queued

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: reposense-deployment-id
        path: |
          ./pr

    - name: Update PR checklist for surge.sh as failure
      if: ${{ failure() }}
      run: ./config/gh-actions/deploy-surge.sh failure
